connector:
    name: oro_importexport
    jobs:
        dotmailer_address_book_import:
            title: orocrm.dotmailer.connector.address_book.job
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_dotmailer.connector.address_book
                        processor: orocrm_dotmailer.importexport.processor.address_book
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25

        dotmailer_campaign_import:
            title: orocrm.dotmailer.connector.campaign.job
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_dotmailer.connector.campaign
                        processor: orocrm_dotmailer.importexport.processor.campaign
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 100

        dotmailer_unsubscribed_contacts_import:
            title: orocrm.dotmailer.connector.unsubscribed_contacts.job
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_dotmailer.connector.unsubscribed_contacts
                        processor: orocrm_dotmailer.importexport.processor.unsubscribed_contacts
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25
                unsubscribed_from_account_contacts_import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                          reader:    orocrm_dotmailer.importexport.reader.unsubscribed_from_account_contacts
                          processor: orocrm_dotmailer.importexport.processor.unsubscribed_from_account_contacts
                          writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25

        dotmailer_new_contacts:
            title: orocrm.dotmailer.connector.contact.job
            type:  import
            steps:
                -
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_dotmailer.connector.contact
                        processor: orocrm_dotmailer.importexport.processor.contact
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 100
