oro_menu_config:
    items:
        orocrm_dotmailer:
            label: 'orocrm.dotmailer.channel_type.label'
            uri: '#'
            extras:
                position: 50
        orocrm_dotmailer_data_field_list:
            label: 'orocrm.dotmailer.datafield.entity_plural_label'
            route: 'orocrm_dotmailer_datafield_index'
            extras:
                routes: ['/^orocrm_dotmailer_datafield_(?!mapping\w+)\w+$/']
        orocrm_dotmailer_data_field_mapping_list:
            label: 'orocrm.dotmailer.datafieldmapping.entity_plural_label'
            route: 'orocrm_dotmailer_datafield_mapping_index'
            extras:
                routes: ['orocrm_dotmailer_datafield_mapping_*']
        orocrm_dotmailer_integration_connection:
            label: 'orocrm.dotmailer.integration.connection.label'
            route: 'orocrm_dotmailer_integration_connection'
            extras:
                routes: ['orocrm_dotmailer_integration_connection']
                position: 10

    tree:
        application_menu:
            children:
                marketing_tab:
                    children:
                        orocrm_dotmailer:
                            children:
                                orocrm_dotmailer_integration_connection: ~
                                orocrm_dotmailer_data_field_list: ~
                                orocrm_dotmailer_data_field_mapping_list: ~

oro_titles:
    orocrm_dotmailer_datafield_index: ~
    orocrm_dotmailer_datafield_create: 'Add Dotmailer Data Field'
    orocrm_dotmailer_datafield_view: '%%datafield.name%%'

    orocrm_dotmailer_datafield_mapping_index: ~
    orocrm_dotmailer_datafield_mapping_create: 'Add Dotmailer Data Field Mapping'
    orocrm_dotmailer_datafield_mapping_update: 'Update Dotmailer Data Field Mapping'

    orocrm_dotmailer_integration_connection: '%%title%%'
