parameters:
    # Entities
    orocrm_dotmailer.entity.transport.class:                          OroCRM\Bundle\DotmailerBundle\Entity\DotmailerTransport
    orocrm_dotmailer.entity.contact.class:                            OroCRM\Bundle\DotmailerBundle\Entity\Contact

    # Integration related services
    orocrm_dotmailer.provider.channel_type.class:                     OroCRM\Bundle\DotmailerBundle\Provider\ChannelType
    orocrm_dotmailer.transport.integration_transport.class:           OroCRM\Bundle\DotmailerBundle\Provider\Transport\DotmailerTransport
    orocrm_dotmailer.transport.resources_factory.class:               OroCRM\Bundle\DotmailerBundle\Provider\Transport\DotmailerResourcesFactory

    # Forms and Extensions
    orocrm_dotmailer.form.type.integration_transport_settings.class:  OroCRM\Bundle\DotmailerBundle\Form\Type\IntegrationSettingsType

    # Data converters
    orocrm_dotmailer.importexport.data_converter.contact.class:       OroCRM\Bundle\DotmailerBundle\ImportExport\DataConverter\ContactDataConverter

    # Strategy
    orocrm_dotmailer.importexport.strategy.add_or_replace.class:      OroCRM\Bundle\DotmailerBundle\ImportExport\Strategy\AddOrReplaceStrategy

    # Processors
    orocrm_dotmailer.importexport.processor.import_abstract.class:    OroCRM\Bundle\DotmailerBundle\ImportExport\Processor\ImportProcessor

    # Connectors
    orocrm_dotmailer.connector.abstract.class:                        OroCRM\Bundle\DotmailerBundle\Provider\Connector\AbstractDotmailerConnector
    orocrm_dotmailer.connector.campaign.class:                        OroCRM\Bundle\DotmailerBundle\Provider\Connector\CampaignsConnector
    orocrm_dotmailer.connector.contact.class:                         OroCRM\Bundle\DotmailerBundle\Provider\Connector\ContactConnector

    # Serializer
    orocrm_dotmailer.importexport.normalizer.enum.class:              OroCRM\Bundle\DotmailerBundle\ImportExport\Serializer\EnumNormalizer

services:
    # Forms and Extensions
    orocrm_dotmailer.form.type.integration_transport_settings:
        class: %orocrm_dotmailer.form.type.integration_transport_settings.class%
        tags:
            - { name: form.type, alias: "orocrm_dotmailer_transport_setting_type" }

    # Integration related services
    orocrm_dotmailer.provider.channel_type:
        class: %orocrm_dotmailer.provider.channel_type.class%
        tags:
            - { name: oro_integration.channel, type: dotmailer }

    orocrm_dotmailer.transport.integration_transport:
        class: %orocrm_dotmailer.transport.integration_transport.class%
        arguments:
            - @orocrm_dotmailer.transport.resources_factory
        tags:
            - { name: oro_integration.transport, type: dotmailer_api, channel_type: dotmailer }

    orocrm_dotmailer.transport.resources_factory:
        class: %orocrm_dotmailer.transport.resources_factory.class%

    # Data converter
    orocrm_dotmailer.importexport.data_converter.contact:
        class: %orocrm_dotmailer.importexport.data_converter.contact.class%

    # Connectors
    orocrm_dotmailer.connector.abstract:
        abstract: true
        arguments:
            - @oro_importexport.context_registry
            - @oro_integration.logger.strategy
            - @oro_integration.provider.connector_context_mediator
        calls:
            - [setManagerRegistry, [@doctrine]]

    orocrm_dotmailer.connector.contact:
        class: %orocrm_dotmailer.connector.contact.class%
        parent: orocrm_dotmailer.connector.abstract
        calls:
            - [setEntityName, [%orocrm_dotmailer.entity.contact.class%]]
        tags:
            - { name: oro_integration.connector, type: contact, channel_type: dotmailer }

    # Strategy
    orocrm_dotmailer.importexport.strategy.add_or_replace:
        class: %orocrm_dotmailer.importexport.strategy.add_or_replace.class%
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Processors
    orocrm_dotmailer.importexport.processor.import_abstract:
        class: %orocrm_dotmailer.importexport.processor.import_abstract.class%
        parent: oro_importexport.processor.import_abstract
        arguments:
            - @oro_importexport.context_registry
        abstract: true

    orocrm_dotmailer.importexport.processor.contact:
        parent: orocrm_dotmailer.importexport.processor.import_abstract
        calls:
            - [setDataConverter, [@orocrm_dotmailer.importexport.data_converter.contact]]
            - [setStrategy, [@orocrm_dotmailer.importexport.strategy.add_or_replace]]
            - [setEntityName, [%orocrm_dotmailer.entity.contact.class%]]

    # Serializer
    orocrm_dotmailer.importexport.normalizer.enum:
        class: %orocrm_dotmailer.importexport.normalizer.enum.class%
        tags:
            - { name: oro_importexport.normalizer, priority: 20 }
