parameters:
    # Entities
    orocrm_dotmailer.entity.transport.class:                          OroCRM\Bundle\DotmailerBundle\Entity\DotmailerTransport
    orocrm_dotmailer.entity.campaign.class:                           OroCRM\Bundle\DotmailerBundle\Entity\Campaign
    orocrm_dotmailer.entity.address_book.class:                       OroCRM\Bundle\DotmailerBundle\Entity\AddressBook
    orocrm_dotmailer.entity.contact.class:                            OroCRM\Bundle\DotmailerBundle\Entity\Contact

    # Integration related services
    orocrm_dotmailer.provider.channel_type.class:                     OroCRM\Bundle\DotmailerBundle\Provider\ChannelType
    orocrm_dotmailer.transport.integration_transport.class:           OroCRM\Bundle\DotmailerBundle\Provider\Transport\DotmailerTransport
    orocrm_dotmailer.transport.resources_factory.class:               OroCRM\Bundle\DotmailerBundle\Provider\Transport\DotmailerResourcesFactory

    # Forms and Extensions
    orocrm_dotmailer.form.type.integration_transport_settings.class:  OroCRM\Bundle\DotmailerBundle\Form\Type\IntegrationSettingsType
    orocrm_dotmailer.form.type.marketing_list_connection.class:       OroCRM\Bundle\DotmailerBundle\Form\Type\MarketingListConnectionType
    orocrm_dotmailer.form.type.integration_select.class:              OroCRM\Bundle\DotmailerBundle\Form\Type\IntegrationSelectType
    orocrm_dotmailer.form.type.address_book_select.class:             OroCRM\Bundle\DotmailerBundle\Form\Type\AddressBookSelectType

    #Form handlers
    orocrm_dotmailer.form.handler.connection_update.class:            OroCRM\Bundle\DotmailerBundle\Form\Handler\ConnectionUpdateFormHandler

    #data converters
    orocrm_dotmailer.importexport.data_converter.address_book.class:          OroCRM\Bundle\DotmailerBundle\ImportExport\DataConverter\AddressBookDataConverter
    orocrm_dotmailer.importexport.data_converter.unsubscribed_contacts.class: OroCRM\Bundle\DotmailerBundle\ImportExport\DataConverter\UnsubscribedContactsDataConverter
    orocrm_dotmailer.importexport.data_converter.campaign.class:              OroCRM\Bundle\DotmailerBundle\ImportExport\DataConverter\CampaignDataConverter

    #reader
    orocrm_dotmailer.importexport.reader.unsubscribed_from_account_contacts.class: OroCRM\Bundle\DotmailerBundle\ImportExport\Reader\UnsubscribedFromAccountContactsReader

    #connectors
    orocrm_dotmailer.connector.abstract.class:                            OroCRM\Bundle\DotmailerBundle\Provider\Connector\AbstractDotmailerConnector
    orocrm_dotmailer.connector.campaign.class:                            OroCRM\Bundle\DotmailerBundle\Provider\Connector\CampaignConnector
    orocrm_dotmailer.connector.address_book.class:                        OroCRM\Bundle\DotmailerBundle\Provider\Connector\AddressBookConnector
    orocrm_dotmailer.connector.unsubscribed_contacts.class:               OroCRM\Bundle\DotmailerBundle\Provider\Connector\UnsubscribedContactsConnector
    orocrm_dotmailer.connector.unsubscribed_from_account_contacts.class:  OroCRM\Bundle\DotmailerBundle\Provider\Connector\UnsubscribedFromAccountContactsConnector

    #strategy
    orocrm_dotmailer.importexport.strategy.add_or_replace.class:                      OroCRM\Bundle\DotmailerBundle\ImportExport\Strategy\AddOrReplaceStrategy
    orocrm_dotmailer.importexport.strategy.import.abstract.class:                     OroCRM\Bundle\DotmailerBundle\ImportExport\Strategy\AbstractImportStrategy
    orocrm_dotmailer.importexport.strategy.unsubscribed_contacts.class:               OroCRM\Bundle\DotmailerBundle\ImportExport\Strategy\UnsubscribedContactsStrategy
    orocrm_dotmailer.importexport.strategy.unsubscribed_from_account_contacts.class:  OroCRM\Bundle\DotmailerBundle\ImportExport\Strategy\UnsubscribedFromAccountStrategy
    orocrm_dotmailer.importexport.strategy.campaign.class:                            OroCRM\Bundle\DotmailerBundle\ImportExport\Strategy\CampaignStrategy

    #processor
    orocrm_dotmailer.importexport.processor.import_abstract.class:    OroCRM\Bundle\DotmailerBundle\ImportExport\Processor\ImportProcessor

    #serializer
    orocrm_dotmailer.importexport.normalizer.enum.class:              OroCRM\Bundle\DotmailerBundle\ImportExport\Serializer\EnumNormalizer
    orocrm.dotmailer.importexport.normalizer.configurable.class:      OroCRM\Bundle\DotmailerBundle\ImportExport\Serializer\ConfigurableEntityNormalizer

    #filters
    orocrm_dotmailer.placeholder.filter.buttons_filter.class:         OroCRM\Bundle\DotmailerBundle\Placeholders\ButtonFilter

    #search handlers
    orocrm_dotmailer.form.autocomplete.list.search_handler.class:     OroCRM\Bundle\DotmailerBundle\Autocomplete\AddressBooksSearchHandler

services:

    # Forms and Extensions
    orocrm_dotmailer.form.type.integration_transport_settings:
        class: %orocrm_dotmailer.form.type.integration_transport_settings.class%
        tags:
            - { name: form.type, alias: "orocrm_dotmailer_transport_setting_type" }

    orocrm_dotmailer.form.type.marketing_list_connection:
        class: %orocrm_dotmailer.form.type.marketing_list_connection.class%
        tags:
            - { name: form.type, alias: "orocrm_dotmailer_marketing_list_connection" }

    orocrm_dotmailer.form.type.integration_select:
        class: %orocrm_dotmailer.form.type.integration_select.class%
        arguments:
            - @doctrine
            - @oro_security.acl_helper
        tags:
            - { name: form.type, alias: "orocrm_dotmailer_integration_select" }

    orocrm_dotmailer.form.type.address_book_select:
        class: %orocrm_dotmailer.form.type.address_book_select.class%
        tags:
            - { name: form.type, alias: "orocrm_dotmailer_address_book_list_select" }

    orocrm_dotmailer.form.autocomplete.list.search_handler:
        class: %orocrm_dotmailer.form.autocomplete.list.search_handler.class%
        arguments:
            - %orocrm_dotmailer.entity.address_book.class%
            - ["name"]
        calls:
            - [initDoctrinePropertiesByManagerRegistry, ["@doctrine"]]
            - [setAclHelper,["@oro_security.acl_helper"]]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: "dotmailer_address_books", acl_resource: "orocrm_email_campaign_view" }

    #Form handlers
    orocrm_dotmailer.form.handler.connection_update:
        class: %orocrm_dotmailer.form.handler.connection_update.class%
        arguments:
            - @doctrine
            - @request
        scope: request

    # Integration related services
    orocrm_dotmailer.provider.channel_type:
        class: %orocrm_dotmailer.provider.channel_type.class%
        tags:
            - { name: oro_integration.channel, type: dotmailer }

    orocrm_dotmailer.transport.integration_transport:
        class: %orocrm_dotmailer.transport.integration_transport.class%
        arguments:
            - @orocrm_dotmailer.transport.resources_factory
        tags:
            - { name: oro_integration.transport, type: dotmailer_api, channel_type: dotmailer }

    orocrm_dotmailer.transport.resources_factory:
        class: %orocrm_dotmailer.transport.resources_factory.class%

    #readers
    orocrm_dotmailer.importexport.reader.unsubscribed_from_account_contacts:
        class: %orocrm_dotmailer.importexport.reader.unsubscribed_from_account_contacts.class%
        arguments:
            - @oro_importexport.context_registry
            - @oro_integration.provider.connector_context_mediator
            - @doctrine

    #connectors
    orocrm_dotmailer.connector.abstract:
        abstract: true
        arguments:
            - @oro_importexport.context_registry
            - @oro_integration.logger.strategy
            - @oro_integration.provider.connector_context_mediator
        calls:
            - [setManagerRegistry, [@doctrine]]

    orocrm_dotmailer.connector.campaign:
        class: %orocrm_dotmailer.connector.campaign.class%
        parent: orocrm_dotmailer.connector.abstract
        calls:
            - [setEntityName, [%orocrm_dotmailer.entity.campaign.class%]]
        tags:
            - { name: oro_integration.connector, type: campaign, channel_type: dotmailer }

    orocrm_dotmailer.connector.address_book:
        class: %orocrm_dotmailer.connector.address_book.class%
        parent: orocrm_dotmailer.connector.abstract
        calls:
            - [setEntityName, [%orocrm_dotmailer.entity.address_book.class%]]
        tags:
            - { name: oro_integration.connector, type: address_book, channel_type: dotmailer }

    orocrm_dotmailer.connector.unsubscribed_contacts:
        class: %orocrm_dotmailer.connector.unsubscribed_contacts.class%
        parent: orocrm_dotmailer.connector.abstract
        calls:
            - [setEntityName, [%orocrm_dotmailer.entity.contact.class%]]
        tags:
            - { name: oro_integration.connector, type: unsubscribed_contacts, channel_type: dotmailer }

    orocrm_dotmailer.connector.unsubscribed_from_account_contacts:
        class: %orocrm_dotmailer.connector.unsubscribed_from_account_contacts.class%
        parent: orocrm_dotmailer.connector.abstract
        calls:
            - [setEntityName, [%orocrm_dotmailer.entity.contact.class%]]

    #data converter
    orocrm_dotmailer.importexport.data_converter.campaign:
        class: %orocrm_dotmailer.importexport.data_converter.campaign.class%

    orocrm_dotmailer.importexport.data_converter.address_book:
        class: %orocrm_dotmailer.importexport.data_converter.address_book.class%

    orocrm_dotmailer.importexport.data_converter.unsubscribed_contacts:
        class: %orocrm_dotmailer.importexport.data_converter.unsubscribed_contacts.class%

    #strategy
    orocrm_dotmailer.importexport.strategy.add_or_replace:
        class: %orocrm_dotmailer.importexport.strategy.add_or_replace.class%
        parent: oro_importexport.strategy.configurable_add_or_replace
        calls:
            - [setOwnerHelper, [@oro_integration.helper.default_owner_helper]]

    orocrm_dotmailer.importexport.strategy.import.abstract:
        class: %orocrm_dotmailer.importexport.strategy.import.abstract.class%
        abstract: true
        calls:
            - [setRegistry, [@doctrine]]

    orocrm_dotmailer.importexport.strategy.unsubscribed_contacts:
        class: %orocrm_dotmailer.importexport.strategy.unsubscribed_contacts.class%
        parent: orocrm_dotmailer.importexport.strategy.import.abstract

    orocrm_dotmailer.importexport.strategy.campaign:
        class: %orocrm_dotmailer.importexport.strategy.campaign.class%
        parent: orocrm_dotmailer.importexport.strategy.add_or_replace

    orocrm_dotmailer.importexport.strategy.unsubscribed_from_account_contacts:
        class: %orocrm_dotmailer.importexport.strategy.unsubscribed_from_account_contacts.class%
        parent: orocrm_dotmailer.importexport.strategy.import.abstract

    #processor
    orocrm_dotmailer.importexport.processor.import_abstract:
        class: %orocrm_dotmailer.importexport.processor.import_abstract.class%
        parent: oro_importexport.processor.import_abstract
        arguments:
            - @oro_importexport.context_registry
        abstract: true

    orocrm_dotmailer.importexport.processor.address_book:
        parent: orocrm_dotmailer.importexport.processor.import_abstract
        calls:
            - [setDataConverter, [@orocrm_dotmailer.importexport.data_converter.address_book]]
            - [setStrategy, [@orocrm_dotmailer.importexport.strategy.add_or_replace]]
            - [setEntityName, [%orocrm_dotmailer.entity.address_book.class%]]

    orocrm_dotmailer.importexport.processor.unsubscribed_contacts:
        parent: orocrm_dotmailer.importexport.processor.import_abstract
        calls:
            - [setDataConverter, [@orocrm_dotmailer.importexport.data_converter.unsubscribed_contacts]]
            - [setStrategy, [@orocrm_dotmailer.importexport.strategy.unsubscribed_contacts]]
            - [setEntityName, [%orocrm_dotmailer.entity.contact.class%]]

    orocrm_dotmailer.importexport.processor.unsubscribed_from_account_contacts:
        parent: orocrm_dotmailer.importexport.processor.import_abstract
        calls:
            - [setDataConverter, [@orocrm_dotmailer.importexport.data_converter.unsubscribed_contacts]]
            - [setStrategy, [@orocrm_dotmailer.importexport.strategy.unsubscribed_from_account_contacts]]
            - [setEntityName, [%orocrm_dotmailer.entity.contact.class%]]

    orocrm_dotmailer.importexport.processor.campaign:
        parent: orocrm_dotmailer.importexport.processor.import_abstract
        calls:
            - [setDataConverter, [@orocrm_dotmailer.importexport.data_converter.campaign]]
            - [setStrategy, [@orocrm_dotmailer.importexport.strategy.campaign]]
            - [setEntityName, [%orocrm_dotmailer.entity.campaign.class%]]

    #serializer
    orocrm_dotmailer.importexport.normalizer.enum:
        class: %orocrm_dotmailer.importexport.normalizer.enum.class%
        tags:
            - { name: oro_importexport.normalizer, priority: 20 }

    orocrm.dotmailer.importexport.normalizer.configurable:
        parent: oro_importexport.serializer.configurable_entity_normalizer
        class: %orocrm.dotmailer.importexport.normalizer.configurable.class%
        calls:
            - [setManagerRegistry, [@doctrine]]
        tags:
            - { name: oro_importexport.normalizer, priority: 20 }

    #filters
    orocrm_dotmailer.placeholder.filter.buttons_filter:
        class: %orocrm_dotmailer.placeholder.filter.buttons_filter.class%
        arguments:
            - @orocrm_marketing_list.provider.contact_information_fields
