OroCRM\Bundle\DotmailerBundle\Entity\DotmailerTransport:
    properties:
        username:
            - NotBlank: ~
            - Length: 255
        password:
            - NotBlank: ~
            - Length: 255