oro_entity:
    entity_aliases:
        OroCRM\Bundle\DotmailerBundle\Entity\Activity:
            alias:        dotmaileractivity
            plural_alias: dotmaileractivities
        OroCRM\Bundle\DotmailerBundle\Entity\AddressBook:
            alias:        dotmaileraddressbook
            plural_alias: dotmaileraddressbook
        OroCRM\Bundle\DotmailerBundle\Entity\AddressBookContact:
            alias:        dotmaileraddressbookcontact
            plural_alias: dotmaileraddressbookcontacts
        OroCRM\Bundle\DotmailerBundle\Entity\AddressBookContactsExport:
            alias:        dotmaileraddressbookcontactsexport
            plural_alias: dotmaileraddressbookcontactsexport
        OroCRM\Bundle\DotmailerBundle\Entity\Campaign:
            alias:        dotmailercampaign
            plural_alias: dotmailercampaigns
        OroCRM\Bundle\DotmailerBundle\Entity\CampaignSummary:
            alias:        dotmailercampaignsummary
            plural_alias: dotmailercampaignsummary
        OroCRM\Bundle\DotmailerBundle\Entity\Contact:
            alias:        dotmailercontact
            plural_alias: dotmailercontacts
