navigation:
    menu_config:
        items:
            orocrm_dotmailer:
                label: 'orocrm.dotmailer.channel_type.label'
                uri: '#'
                extras:
                    position: 50
            orocrm_dotmailer_data_field_list:
                label: 'orocrm.dotmailer.datafield.entity_plural_label'
                route: 'orocrm_dotmailer_datafield_index'
                extras:
                    routes: ['orocrm_dotmailer_datafield_*']

        tree:
            application_menu:
                children:
                    marketing_tab:
                        children:
                          orocrm_dotmailer:
                              children:
                                  orocrm_dotmailer_data_field_list: ~

    titles:
        orocrm_dotmailer_datafield_index: ~
        orocrm_dotmailer_datafield_create: 'Add Dotmailer Data Field'
        orocrm_dotmailer_datafield_view: '%%datafield.name%%'
