placeholders:
    placeholders:
        view_navButtons_before:
            items:
                oro_dotmailer_marketing_list_buttons: ~
        view_content_data_email_campaign_status:
            items:
                oro_dotmailer_emailcampaign_stats: ~
        marketing_list_sync_info:
            items:
                oro_dotmailer_marketing_list_sync_data: ~

    items:
        oro_dotmailer_marketing_list_buttons:
            action: OroDotmailerBundle:AddressBook:connectionButtons
            applicable: "@oro_dotmailer.placeholder.filter.buttons_filter->isApplicable($entity$)"

        oro_dotmailer_emailcampaign_stats:
            action: OroDotmailerBundle:Dotmailer:emailCampaignStats
            applicable: "@oro_dotmailer.placeholder.filter.email_campaign->isApplicableOnEmailCampaign($entity$)"

        oro_dotmailer_marketing_list_sync_data:
            action: OroDotmailerBundle:Dotmailer:marketingListSyncStatus
            applicable: "@oro_dotmailer.placeholder.filter.sync_status->isApplicableOnMarketingList($marketingList$)"
