orocrm.dotmailer_datafield_api:
    resource: "@OroCRMDotmailerBundle/Controller/Api/Rest/DataFieldController.php"
    type:     rest
orocrm.dotmailer_datafield_mapping_api:
    resource: "@OroCRMDotmailerBundle/Controller/Api/Rest/DataFieldMappingController.php"
    type:     rest

