oro_dotmailer_bundle:
    resource:     "@OroDotmailerBundle/Controller"
    type:         annotation
    prefix:       /dotmailer

oro_dotmailer_oauth_callback:
    path:         /dotmailer/oauth/callback
    defaults:     { _controller: OroDotmailerBundle:Oauth:callback }
    schemes:      [https]
