system_configuration:
    groups:
        dotmailer_settings:
            title: oro.dotmailer.configuration.dotmailer_settings
            icon:  icon-envelope-alt

        synchronization_dotmailer_settings:
            title: oro.dotmailer.configuration.dotmailer_synchronization

    fields:
        oro_dotmailer.datafields_sync_interval:
            data_type: string
            type: text
            priority: 10
            options:
                label:          oro.dotmailer.configuration.datafields_sync_interval
                tooltip:        oro.dotmailer.configuration.datafields_sync_interval.tooltip
                required: false

    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            dotmailer_settings:
                                priority: -20
                                children:
                                    synchronization_dotmailer_settings:
                                        priority: 10
                                        children:
                                            - oro_dotmailer.datafields_sync_interval
